name: my page

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  login-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Deploy to GitHub Pages
        if: always()
        uses: crazy-max/ghaction-github-pages@v3
        with:
            target_branch: gh-pages
            build_dir: ./src/
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
